October 14 2025 UIC Release UIC - 6.4.181
October 14 2025 UIC Release
UIC - 6.4.181
Bug Fixes

- Fix an issue with Uncaught TypeError: t.publishOwnership is not a function in domCaptureService.

Improvements:

- None.

Our environment for this release:

- MacOS 15.5

Known Issues

- Replay does not support iFrames inside ShadowDoms yet.